name: deploy

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Building...'
      uses: reuixiy/hugo-deploy@v1
      env:
        DEPLOY_REPO: cuterebro/cuterebro.github.io
        DEPLOY_BRANCH: gh-pages
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        TZ: Europe/Moscow